name: Add comment on a pull request about the plugin package
# Based on work from https://github.com/orgs/community/discussions/51403#discussioncomment-5535167
on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Creating plugin package in the PR'

jobs:
  comment:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 10 seconds
        run: sleep 10

      - name: List all available artifact
        run: |
          echo "Listing all artifacts for the current workflow run..."

          # Get the current workflow run ID
          run_id=${{ github.run_id }}
          repo=${{ github.repository }}

          # Make a GitHub API call to list artifacts
          response=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$repo/actions/runs/$run_id/artifacts")

          # Extract artifact names from the response
          artifact_names=$(echo "$response" | jq -r '.artifacts[].name')

          # Display the artifact names
          echo "Artifacts:"
          echo "$artifact_names"

      - name: Download PR number artifact
        uses: actions/download-artifact@v4
        with:
          name: pr_number
          path: ./pr_number

      - name: Download artifact URL file
        uses: actions/download-artifact@v4
        with:
          name: artifact_url
          path: ./artifact_url

      - name: Read the pr number artifact
        id: pr_number_reader
        run: |
          PR_NUMBER=$(cat ./pr_number/pr_number.txt)
          echo "PR number: $PR_NUMBER"
          echo "::set-output name=pr_number::$PR_NUMBER"

      - name: Read the artifact URL
        id: artifact_url_reader
        run: |
          ARTIFACT_URL=$(cat ./artifact_url/artifact_url.txt)
          echo "Artifact URL: $ARTIFACT_URL"
          echo "::set-output name=artifact_url::$ARTIFACT_URL"

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ steps.pr_number_reader.outputs.pr_number }}
          comment-author: 'github-actions[bot]'
      - name: Update Comment
        env:
          ARTIFACT_URL: "${{ steps.artifact_url_reader.outputs.artifact_url }}"
          HEAD_SHA: "${{ github.event.head_sha }}"
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ github.token }}
          issue-number:  ${{ steps.pr_number_reader.outputs.pr_number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: |-
            ![badge]
            
            Plugin zip package for the changes in this PR has been successfully built!.
            
            Download the plugin zip file from here ${{ env.ARTIFACT_URL }}
            
            [badge]: https://img.shields.io/badge/package_build-success-green
