name: Creating plugin package and comment in the PR

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  create-package:
    runs-on: ubuntu-22.04
    container:
      image: qgis/qgis:release-3_34
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fix Python command
        run: apt-get install python-is-python3

      - name: Install python
        uses: actions/setup-python@v4

      - name: Install plugin dependencies
        run: pip install -r requirements-dev.txt

      - name: Get unique identifier
        id: get-identifier
        run: |
          echo "::set-output name=PACKAGE_ID::$(python -c "import uuid; print(str(uuid.uuid4())[:4])")"

      - name: Generate zip file
        run: |
          python admin.py build --output-directory ${{ format(
          'docs/plugin/package/qgis_gea_plugin_{0}_{1}/qgis_gea_plugin/',
          github.event.pull_request.head.ref,
          steps.get-identifier.outputs.PACKAGE_ID) }}

      - name: Plugin path details
        id: get-zip-details
        run: |
          echo "::set-output name=ZIP_PATH::docs/plugin/package/$(ls docs/plugin/package)\n"
          echo "::set-output name=ZIP_NAME::$(ls docs/plugin/package)"

      - name: Uploading plugin build
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get-zip-details.outputs.ZIP_NAME }}
          path: ${{ steps.get-zip-details.outputs.ZIP_PATH }}

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.number }}
          comment-author: 'github-actions[bot]'

      - name: Update Comment
        env:
          HEAD_SHA: "${{ github.event.head_sha }}"
          ARTIFACT_URL: ${{ steps.artifact-upload-step.outputs.artifact-url }}

        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ github.token }}
          issue-number: ${{ github.event.number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: |-
            ![badge]	
            
            Plugin zip package for the changes in this PR has been successfully built!.	
            
            Download the plugin zip file here ${{ env.ARTIFACT_URL }}	
            
            [badge]: https://img.shields.io/badge/package_build-success-green	
